---
title: "Homework2"
author: "Yang Zhao - yz4717"
date: "2023-09-30"
output: 
  github_document:
    toc : True
    toc_depth : 2
---

```{r import_function, message=FALSE}
library(tidyverse)
library(readxl)
```

## Question 1

```{r input_data_pols}
pols_df = read_csv("pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, "-",into = c("year","month","day")) |> 
  mutate(
    month = case_match(
      month, 
      "01" ~ "jan",
      "02" ~ "feb",
      "03" ~ "mar",
      "04" ~ "apr",
      "05" ~ "may",
      "06" ~ "jun",
      "07" ~ "jul",
      "08" ~ "aug",
      "09" ~ "sep",
      "10" ~ "oct", 
      "11" ~ "nov", 
      "12" ~ "dec")) |> 
  mutate(president = recode(
    prez_gop, "0" = "dem",
    "1" = "gop", "2" = "gop")) |> 
  select(-prez_gop,-day,-prez_dem)

pols_df|> head()

```
This data frame's size is `r nrow(pols_df)` * `r ncol(pols_df)`


```{r input_data_snp,message=FALSE}


snp_df = read_csv("snp.csv",
                  col_types = cols(Date = col_date(format = "%m/%d/%y"))) |> 
  janitor::clean_names() |> 
  separate(date,"/",into=c("month","day","year"))|> 
  select(year,month,close) |> 
  mutate(
    year = if_else(year<=15 , year+2000,year+1900)
  )

```

## ??????


```{r input_data_umploy, message=FALSE}
umploy_df = read_csv("unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(jan:dec,
               names_to = "month",
               values_to = "umploy")

```


```{r merging_df_Q1}
pols_df$year = as.double(pols_df$year)
snp_df$year = as.double(snp_df$year)

merged_df = pols_df |>
  left_join(snp_df) |> 
  left_join(umploy_df)

(merged_df)
```


## Question 2
```{r Q2_input_mrt}

mrt_df = read_excel(
    "202309 Trash Wheel Collection Data.xlsx",
  cell_cols("A:N"),
  sheet = "Mr. Trash Wheel") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered = weight_tons*500/30,
         wheel = c("mr"))|> 
  relocate(wheel,dumpster,year,month)

  # select(-glass_bottles,-grocery_bags,-chip_bags,-sports_balls)

mrt_df$year = as.double(mrt_df$year)

```

```{r Q2_input_prof}

proft_df = read_excel(
  "202309 Trash Wheel Collection Data.xlsx",
  range = cell_cols("A:M"),
  sheet = "Professor Trash Wheel") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered = weight_tons*500/30,
         wheel = c("prof"))|> 
  relocate(wheel,dumpster,year,month)

  # select(-glass_bottles,-grocery_bags,-chip_bags)

head(proft_df)
```


```{r Q2_input_gwy}

gwyt_df = read_excel(
  "202309 Trash Wheel Collection Data.xlsx",
  range = cell_cols("A:K"),
  sheet = "Gwynnda Trash Wheel") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered = weight_tons*500/30,
         wheel = c("gwy"))|> 
  relocate(wheel,dumpster,year,month) 

  # select(-plastic_bags)

head(gwyt_df)

```

```{r q2_merged}
q2_merged = bind_rows(gwyt_df,mrt_df,proft_df) |> 
  separate(date,"-",into = c("year1","month1","day")) |> 
  select(-year1,-month1) |> 
  relocate(year,month,day) |> 
  arrange(year,month,day)

head(q2_merged)
```

##Question 3

```{r}
base_df = read_csv("MCI_baseline.csv",skip = 1) |> 
  janitor::clean_names() |> 
  mutate(sex = case_match(sex,
                          1~"male",
                          0~"female"),
         apoe4 = case_match(apoe4,
                            1~"carrier",
                            0~"non_carrier")) |> 
  filter(current_age <age_at_onset | 
           age_at_onset==".") |> 
  mutate(age_at_onset = ifelse(age_at_onset == ".", NA, age_at_onset))
```


```{r, message=FALSE}
amy_df = read_csv("mci_amyloid.csv",skip = 1) |> 
  janitor::clean_names() |> 
  rename("id" = "study_id") |> 
  pivot_longer(baseline:time_8,
               names_to = "time",
               values_to = "value") |> 
  mutate(time = case_match(
    time,
    "baseline"~0,
    "time_2"~2,
    "time_4"~4,
    "time_6"~6,
    "time_8"~8
  ))

q3_only1 = anti_join(base_df,amy_df)
q3_only2 = anti_join(amy_df,base_df)
q3_merged_df = inner_join(base_df,amy_df,by = "id")
```

`r sum(base_df$sex =="female" & base_df$apoe4 == "carrier")/sum(base_df$sex == "female")`
